# Loads default set of integrations. Do not remove.
default_config:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

lovelace:
  dashboards:
    db-dev:
      mode: yaml
      title: development
      icon: mdi:developer-board
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace-dev.yaml
    db-minimalist:
      mode: yaml
      title: My Home
      icon: mdi:flower
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace.yaml
    db-01:
      mode: yaml
      title: !secret 01_kid_name
      icon: mdi:teddy-bear
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace-01.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml
lock: !include lock.yaml
group: !include groups.yaml

smartir:
  check_updates: false
