# Loads default set of integrations. Do not remove.
default_config:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

lovelace:
  dashboards:
    db-dev:
      mode: yaml
      title: development
      icon: mdi:developer-board
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace-dev.yaml
    db-minimalist-mobile:
      mode: yaml
      title: mini-mobile
      icon: mdi:cellphone
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace.yaml
    db-minimalist-tablet:
      mode: yaml
      title: mini-tablet
      icon: mdi:tablet
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace-tablet.yaml
    db-01:
      mode: yaml
      title: !secret 01_kid_name
      icon: mdi:teddy-bear
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace-01.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
climate: !include climate.yaml
group: !include groups.yaml
lock: !include lock.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include sensors.yaml

smartir:
  check_updates: false

automation wake_up_screen:
  - alias: Wake up screenblet on motion
    description: Wake up the device screen when motion is detected
    initial_state: true
    triggers:
      trigger: state
      entity_id: !secret camera_front_door_motion
      to: "on"
    condition: []
    actions:
      action: !secret tablet_notify
      data:
        message: command_screen_on
    mode: single
